import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "./_components/nav/MainNav";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex justify-between m-1">
          <MainNav></MainNav>
          {/* <LoginOrOut></LoginOrOut> */}
          <Toaster />
        </div>
        <div className="flex flex-col items-center">{children}</div>
      </body>
    </html>
  );
}
