import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "./_components/nav/MainNav";
import { LoginOrOut } from "./_components/authenticate/Authentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex justify-between m-1">
          <MainNav></MainNav>
          <LoginOrOut></LoginOrOut>
        </div>
        {children}
      </body>
    </html>
  );
}
